apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: api
        image: filesureregistry01.azurecr.io/api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
          name: api
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_URI
        - name: AZURE_BLOB_CONN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AZURE_BLOB_CONN
        - name: AZURE_CONTAINER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AZURE_CONTAINER
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: api
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: api
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - name: api
    port: 5001
    targetPort: 5001
  type: ClusterIP